// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VA.Infrastructure.Data;

namespace VA.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20210906215759_first-migration")]
    partial class firstmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .IsUnicode(false)
                        .HasColumnType("varchar(900)")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("role_name_index")
                        .HasFilter("[normalized_name] IS NOT NULL");

                    b.ToTable("asp_net_roles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("claim_value");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(900)")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("asp_net_role_claims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .IsUnicode(false)
                        .HasColumnType("varchar(900)")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("email_index");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("user_name_index")
                        .HasFilter("[normalized_user_name] IS NOT NULL");

                    b.ToTable("asp_net_users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("claim_value");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(900)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("asp_net_user_claims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .IsUnicode(false)
                        .HasColumnType("varchar(900)")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .IsUnicode(false)
                        .HasColumnType("varchar(900)")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("provider_display_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(900)")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("asp_net_user_logins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .IsUnicode(false)
                        .HasColumnType("varchar(900)")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .IsUnicode(false)
                        .HasColumnType("varchar(900)")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("asp_net_user_roles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .IsUnicode(false)
                        .HasColumnType("varchar(900)")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .IsUnicode(false)
                        .HasColumnType("varchar(900)")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .IsUnicode(false)
                        .HasColumnType("varchar(900)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("asp_net_user_tokens");
                });

            modelBuilder.Entity("VA.Domain.Candidato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("alterado_em");

                    b.Property<DateTime?>("CadastradoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("cadastrado_em");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int")
                        .HasColumnName("perfil_id");

                    b.Property<int?>("UsuarioAlteracao")
                        .HasColumnType("int")
                        .HasColumnName("usuario_alteracao");

                    b.Property<int?>("UsuarioCriacao")
                        .HasColumnType("int")
                        .HasColumnName("usuario_criacao");

                    b.Property<int>("VagaId")
                        .HasColumnType("int")
                        .HasColumnName("vaga_id");

                    b.HasKey("Id")
                        .HasName("pk_candidato");

                    b.HasIndex("PerfilId")
                        .HasDatabaseName("ix_candidato_perfil_id");

                    b.HasIndex("VagaId")
                        .HasDatabaseName("ix_candidato_vaga_id");

                    b.ToTable("candidato");
                });

            modelBuilder.Entity("VA.Domain.Cidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("alterado_em");

                    b.Property<DateTime?>("CadastradoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("cadastrado_em");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int")
                        .HasColumnName("estado_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<int?>("UsuarioAlteracao")
                        .HasColumnType("int")
                        .HasColumnName("usuario_alteracao");

                    b.Property<int?>("UsuarioCriacao")
                        .HasColumnType("int")
                        .HasColumnName("usuario_criacao");

                    b.HasKey("Id")
                        .HasName("pk_cidade");

                    b.HasIndex("EstadoId")
                        .HasDatabaseName("ix_cidade_estado_id");

                    b.ToTable("cidade");
                });

            modelBuilder.Entity("VA.Domain.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("alterado_em");

                    b.Property<DateTime?>("CadastradoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("cadastrado_em");

                    b.Property<int>("CidadeId")
                        .HasColumnType("int")
                        .HasColumnName("cidade_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<int?>("UsuarioAlteracao")
                        .HasColumnType("int")
                        .HasColumnName("usuario_alteracao");

                    b.Property<int?>("UsuarioCriacao")
                        .HasColumnType("int")
                        .HasColumnName("usuario_criacao");

                    b.HasKey("Id")
                        .HasName("pk_empresa");

                    b.HasIndex("CidadeId")
                        .HasDatabaseName("ix_empresa_cidade_id");

                    b.ToTable("empresa");
                });

            modelBuilder.Entity("VA.Domain.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("alterado_em");

                    b.Property<DateTime?>("CadastradoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("cadastrado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<int?>("UsuarioAlteracao")
                        .HasColumnType("int")
                        .HasColumnName("usuario_alteracao");

                    b.Property<int?>("UsuarioCriacao")
                        .HasColumnType("int")
                        .HasColumnName("usuario_criacao");

                    b.HasKey("Id")
                        .HasName("pk_estado");

                    b.ToTable("estado");
                });

            modelBuilder.Entity("VA.Domain.Experiencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("alterado_em");

                    b.Property<DateTime?>("CadastradoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("cadastrado_em");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_fim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_inicio");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int")
                        .HasColumnName("perfil_id");

                    b.Property<int?>("UsuarioAlteracao")
                        .HasColumnType("int")
                        .HasColumnName("usuario_alteracao");

                    b.Property<int?>("UsuarioCriacao")
                        .HasColumnType("int")
                        .HasColumnName("usuario_criacao");

                    b.HasKey("Id")
                        .HasName("pk_experiencia");

                    b.HasIndex("PerfilId")
                        .HasDatabaseName("ix_experiencia_perfil_id");

                    b.ToTable("experiencia");
                });

            modelBuilder.Entity("VA.Domain.Habilidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("alterado_em");

                    b.Property<DateTime?>("CadastradoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("cadastrado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int")
                        .HasColumnName("perfil_id");

                    b.Property<int?>("UsuarioAlteracao")
                        .HasColumnType("int")
                        .HasColumnName("usuario_alteracao");

                    b.Property<int?>("UsuarioCriacao")
                        .HasColumnType("int")
                        .HasColumnName("usuario_criacao");

                    b.HasKey("Id")
                        .HasName("pk_habilidade");

                    b.HasIndex("PerfilId")
                        .HasDatabaseName("ix_habilidade_perfil_id");

                    b.ToTable("habilidade");
                });

            modelBuilder.Entity("VA.Domain.Like", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("alterado_em");

                    b.Property<DateTime?>("CadastradoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("cadastrado_em");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int")
                        .HasColumnName("perfil_id");

                    b.Property<int?>("UsuarioAlteracao")
                        .HasColumnType("int")
                        .HasColumnName("usuario_alteracao");

                    b.Property<int?>("UsuarioCriacao")
                        .HasColumnType("int")
                        .HasColumnName("usuario_criacao");

                    b.Property<int>("VagaId")
                        .HasColumnType("int")
                        .HasColumnName("vaga_id");

                    b.HasKey("Id")
                        .HasName("pk_like");

                    b.HasIndex("PerfilId")
                        .HasDatabaseName("ix_like_perfil_id");

                    b.HasIndex("VagaId")
                        .HasDatabaseName("ix_like_vaga_id");

                    b.ToTable("like");
                });

            modelBuilder.Entity("VA.Domain.Pagina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("alterado_em");

                    b.Property<DateTime?>("CadastradoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("cadastrado_em");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int")
                        .HasColumnName("empresa_id");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int")
                        .HasColumnName("perfil_id");

                    b.Property<int?>("UsuarioAlteracao")
                        .HasColumnType("int")
                        .HasColumnName("usuario_alteracao");

                    b.Property<int?>("UsuarioCriacao")
                        .HasColumnType("int")
                        .HasColumnName("usuario_criacao");

                    b.HasKey("Id")
                        .HasName("pk_pagina");

                    b.HasIndex("EmpresaId")
                        .IsUnique()
                        .HasDatabaseName("ix_pagina_empresa_id");

                    b.HasIndex("PerfilId")
                        .HasDatabaseName("ix_pagina_perfil_id");

                    b.ToTable("pagina");
                });

            modelBuilder.Entity("VA.Domain.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("alterado_em");

                    b.Property<DateTime?>("CadastradoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("cadastrado_em");

                    b.Property<int>("CidadeId")
                        .HasColumnType("int")
                        .HasColumnName("cidade_id");

                    b.Property<string>("Curriculo")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("curriculo");

                    b.Property<string>("DDD")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("ddd");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("telefone");

                    b.Property<int?>("UsuarioAlteracao")
                        .HasColumnType("int")
                        .HasColumnName("usuario_alteracao");

                    b.Property<int?>("UsuarioCriacao")
                        .HasColumnType("int")
                        .HasColumnName("usuario_criacao");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_perfil");

                    b.HasIndex("CidadeId")
                        .HasDatabaseName("ix_perfil_cidade_id");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("ix_perfil_usuario_id");

                    b.ToTable("perfil");
                });

            modelBuilder.Entity("VA.Domain.Senioridade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("alterado_em");

                    b.Property<DateTime?>("CadastradoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("cadastrado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<int?>("UsuarioAlteracao")
                        .HasColumnType("int")
                        .HasColumnName("usuario_alteracao");

                    b.Property<int?>("UsuarioCriacao")
                        .HasColumnType("int")
                        .HasColumnName("usuario_criacao");

                    b.HasKey("Id")
                        .HasName("pk_senioridade");

                    b.ToTable("senioridade");
                });

            modelBuilder.Entity("VA.Domain.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("alterado_em");

                    b.Property<DateTime?>("CadastradoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("cadastrado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("senha");

                    b.Property<int?>("UsuarioAlteracao")
                        .HasColumnType("int")
                        .HasColumnName("usuario_alteracao");

                    b.Property<int?>("UsuarioCriacao")
                        .HasColumnType("int")
                        .HasColumnName("usuario_criacao");

                    b.HasKey("Id")
                        .HasName("pk_usuario");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("VA.Domain.Vaga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("alterado_em");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("CadastradoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("cadastrado_em");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("descricao");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int")
                        .HasColumnName("empresa_id");

                    b.Property<int>("SenioridadeId")
                        .HasColumnType("int")
                        .HasColumnName("senioridade_id");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("titulo");

                    b.Property<int?>("UsuarioAlteracao")
                        .HasColumnType("int")
                        .HasColumnName("usuario_alteracao");

                    b.Property<int?>("UsuarioCriacao")
                        .HasColumnType("int")
                        .HasColumnName("usuario_criacao");

                    b.HasKey("Id")
                        .HasName("pk_vaga");

                    b.HasIndex("EmpresaId")
                        .HasDatabaseName("ix_vaga_empresa_id");

                    b.HasIndex("SenioridadeId")
                        .IsUnique()
                        .HasDatabaseName("ix_vaga_senioridade_id");

                    b.ToTable("vaga");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VA.Domain.Candidato", b =>
                {
                    b.HasOne("VA.Domain.Perfil", "Perfil")
                        .WithMany("Candidaturas")
                        .HasForeignKey("PerfilId")
                        .HasConstraintName("fk_candidato_perfil_perfil_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VA.Domain.Vaga", "Vaga")
                        .WithMany("Candidatos")
                        .HasForeignKey("VagaId")
                        .HasConstraintName("fk_candidato_vaga_vaga_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Perfil");

                    b.Navigation("Vaga");
                });

            modelBuilder.Entity("VA.Domain.Cidade", b =>
                {
                    b.HasOne("VA.Domain.Estado", "Estado")
                        .WithMany("Cidades")
                        .HasForeignKey("EstadoId")
                        .HasConstraintName("fk_cidade_estado_estado_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("VA.Domain.Empresa", b =>
                {
                    b.HasOne("VA.Domain.Cidade", "Cidade")
                        .WithMany("Empresas")
                        .HasForeignKey("CidadeId")
                        .HasConstraintName("fk_empresa_cidade_cidade_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cidade");
                });

            modelBuilder.Entity("VA.Domain.Experiencia", b =>
                {
                    b.HasOne("VA.Domain.Perfil", "Perfil")
                        .WithMany("Experiencias")
                        .HasForeignKey("PerfilId")
                        .HasConstraintName("fk_experiencia_perfil_perfil_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("VA.Domain.Habilidade", b =>
                {
                    b.HasOne("VA.Domain.Perfil", "Perfil")
                        .WithMany("Habilidades")
                        .HasForeignKey("PerfilId")
                        .HasConstraintName("fk_habilidade_perfil_perfil_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("VA.Domain.Like", b =>
                {
                    b.HasOne("VA.Domain.Perfil", "Perfil")
                        .WithMany("Likes")
                        .HasForeignKey("PerfilId")
                        .HasConstraintName("fk_like_perfil_perfil_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VA.Domain.Vaga", "Vaga")
                        .WithMany("Likes")
                        .HasForeignKey("VagaId")
                        .HasConstraintName("fk_like_vaga_vaga_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Perfil");

                    b.Navigation("Vaga");
                });

            modelBuilder.Entity("VA.Domain.Pagina", b =>
                {
                    b.HasOne("VA.Domain.Empresa", "Empresa")
                        .WithOne("Pagina")
                        .HasForeignKey("VA.Domain.Pagina", "EmpresaId")
                        .HasConstraintName("fk_pagina_empresa_empresa_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VA.Domain.Perfil", "Perfil")
                        .WithMany("Paginas")
                        .HasForeignKey("PerfilId")
                        .HasConstraintName("fk_pagina_perfil_perfil_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("VA.Domain.Perfil", b =>
                {
                    b.HasOne("VA.Domain.Cidade", "Cidade")
                        .WithMany("Perfils")
                        .HasForeignKey("CidadeId")
                        .HasConstraintName("fk_perfil_cidade_cidade_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VA.Domain.Usuario", "Usuario")
                        .WithOne("Perfil")
                        .HasForeignKey("VA.Domain.Perfil", "UsuarioId")
                        .HasConstraintName("fk_perfil_usuario_usuario_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cidade");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VA.Domain.Vaga", b =>
                {
                    b.HasOne("VA.Domain.Empresa", "Empresa")
                        .WithMany("Vagas")
                        .HasForeignKey("EmpresaId")
                        .HasConstraintName("fk_vaga_empresa_empresa_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VA.Domain.Senioridade", "Senioridade")
                        .WithOne("Vaga")
                        .HasForeignKey("VA.Domain.Vaga", "SenioridadeId")
                        .HasConstraintName("fk_vaga_senioridade_senioridade_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Senioridade");
                });

            modelBuilder.Entity("VA.Domain.Cidade", b =>
                {
                    b.Navigation("Empresas");

                    b.Navigation("Perfils");
                });

            modelBuilder.Entity("VA.Domain.Empresa", b =>
                {
                    b.Navigation("Pagina");

                    b.Navigation("Vagas");
                });

            modelBuilder.Entity("VA.Domain.Estado", b =>
                {
                    b.Navigation("Cidades");
                });

            modelBuilder.Entity("VA.Domain.Perfil", b =>
                {
                    b.Navigation("Candidaturas");

                    b.Navigation("Experiencias");

                    b.Navigation("Habilidades");

                    b.Navigation("Likes");

                    b.Navigation("Paginas");
                });

            modelBuilder.Entity("VA.Domain.Senioridade", b =>
                {
                    b.Navigation("Vaga");
                });

            modelBuilder.Entity("VA.Domain.Usuario", b =>
                {
                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("VA.Domain.Vaga", b =>
                {
                    b.Navigation("Candidatos");

                    b.Navigation("Likes");
                });
#pragma warning restore 612, 618
        }
    }
}
